<a href="https://colab.research.google.com/github/PanchitaWallatri/Data-ana/blob/main/Intro_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##import libs

In [ ]:
import numpy as np
import pandas as pd
import io

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.metrics import mean_squared_error

## Dataset

In [ ]:
csv_data = """
x1	x2	y
1	2	14
2	3	18
3	4	24
4	5	32
"""

In [ ]:
csv_data

'\nx1\tx2\ty\n1\t2\t14\n2\t3\t18\n3\t4\t24\n4\t5\t32\n'

In [ ]:
df = pd.read_csv(io.StringIO(csv_data), sep="\t")

In [ ]:
df

x1  x2   y
0   1   2  14
1   2   3  18
2   3   4  24
3   4   5  32

##Input & Output

In [ ]:
X = df[["x1", "x2"]]

In [ ]:
X

x1  x2
0   1   2
1   2   3
2   3   4
3   4   5

In [ ]:
y = df["y"]

In [ ]:
y

0    14
1    18
2    24
3    32
Name: y, dtype: int64

##linear model

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
model.coef_

array([3., 3.])

In [ ]:
model.intercept_

4.000000000000007

In [ ]:
# y = 4 + 3*x1 + 3*x2

##Evaluation

In [ ]:
model.predict([(1,2), (2,3),(10,30)])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([ 13.,  19., 124.])

In [ ]:
model.predict(X)

array([13., 19., 25., 31.])

In [ ]:
y_pred=model.predict(X)

In [ ]:
y_pred

array([13., 19., 25., 31.])

In [ ]:
y

0    14
1    18
2    24
3    32
Name: y, dtype: int64

In [ ]:
y - y_pred

0    1.0
1   -1.0
2   -1.0
3    1.0
Name: y, dtype: float64

In [ ]:
rmse = np.sqrt(((y - y_pred)**2).mean())

In [ ]:
rmse

1.0000000000000009

In [ ]:
mean_squared_error(y , y_pred,squared=False)

1.0000000000000009

##Train-Test Split

In [ ]:
df

x1  x2   y
0   1   2  14
1   2   3  18
2   3   4  24
3   4   5  32

In [ ]:
X

x1  x2
0   1   2
1   2   3
2   3   4
3   4   5

In [ ]:
y

0    14
1    18
2    24
3    32
Name: y, dtype: int64

In [ ]:
X_train = X.loc[0:2]
y_train = y.loc[0:2]

X_test = X.loc[[3]]
y_test = y.loc[3]

In [ ]:
y_test

32

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
print(model.coef_)
print(model.intercept_)

[3.07142857 3.07142857]
3.928571428571434


In [ ]:
y_pred = model.predict(X_test)
y_pred

array([25.42857143])

In [ ]:
y_test

2    24
Name: y, dtype: int64

In [ ]:
mean_squared_error(y_test , y_pred,squared=False)

1.428571428571427

## K-Fold Cross-Validation

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
kf = KFold(n_splits=4, shuffle=True)

In [ ]:
kf.get_n_splits(X)

4

In [ ]:
for train_index, test_index in kf.split(X):
  print("train_index =", train_index)
  print("test_index =", test_index)
  print(" -------------- ")

train_index = [0 1 2]
test_index = [3]
 -------------- 
train_index = [0 1 3]
test_index = [2]
 -------------- 
train_index = [1 2 3]
test_index = [0]
 -------------- 
train_index = [0 2 3]
test_index = [1]
 -------------- 


In [ ]:
y.loc[train_index]

0    14
2    24
3    32
Name: y, dtype: int64

In [ ]:
y.loc[test_index]

1    18
Name: y, dtype: int64

In [ ]:
i=0
RMSEs = []

for train_index, test_index in kf.split(X):
  X_train = X.loc[train_index]
  X_test = X.loc[test_index]
  y_train = y.loc[train_index]
  y_test = y.loc[test_index]

  model = LinearRegression()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  rmse_i = mean_squared_error(y_test , y_pred,squared=False)

  RMSEs.append(rmse_i)

  i+=1
  print('round',i)
  print('RMSE =',rmse_i)
  print('----------------')

round 1
RMSE = 1.428571428571427
----------------
round 2
RMSE = 3.333333333333327
----------------
round 3
RMSE = 1.4285714285714306
----------------
round 4
RMSE = 3.3333333333333357
----------------


In [ ]:
RMSEs

[1.428571428571427, 3.333333333333327, 3.3333333333333357, 1.4285714285714306]

In [ ]:
np.mean(RMSEs)

2.38095238095238

In [ ]:
###Real implementation
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()